/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PublicTransportFinder;

import PublicTransportFinder.view.JavaFXApp;

public class Start {
    public static void main(String[] args) {
        JavaFXApp.main(args);
    }
}
